### ISSUE TITLE
Feren Synaptic Update Diff text box too small

### ISSUE THREAD

**Issue by venomdev** [feren-OS/Feren-OS-Major-Updater#2]
The diff text box is only 2 lines high even in full window mode.

![image](https://user-images.githubusercontent.com/43404319/89244445-a8b8eb00-d645-11ea-9fd6-8ca180f681e2.png)

Can you resize the text box dynamically please?
It's difficult to see all the changes.

**Comment by dominichayesferen** [comment]
This isn't a bug with this project, this is a bug with Synaptic. One should report it to Synaptic's own bug tracker. Closing...
