### ISSUE TITLE
Clunky description

### ISSUE THREAD

**Issue by nothingneko** [feren-OS/Feren-OS-Major-Updater#4]
I noticed that the explanation was a bit clunky, so I rewrote it

"Feren OS classic has been discontinued. You can continue to use your installation, but you will no longer receive any updates. Switch to the new Feren OS to get the latest and greatest, but if you would rather keep your Cinnamon desktop you can switch to Linux Mint."

I think this works a bit better, thoughts?

**Comment by dominichayesferen** [comment]
The text has been finalised, and the product released, hence this issue shall now be closed.
